openapi: 3.1.0
info:
  version: 1.0.0
  title: Comtacts Web App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    Contacts Web App is a web application for managing user contacts.
    The app allows users to register, log in, add, edit, delete and view contacts. The application also supports integration with Google OAuth for user authorization.
tags:
  - name: Auth
    description: Operations with users (registration, login, exit, etc.)
  - name: Contacts
    description: Operations with contacts (adding, editing, deleting, viewing)
servers:
  - url: http://localhost:3000
  - url: https://hw6-email-and-images-hluh.onrender.com
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh_token.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/auth/send-reset-email.yaml'
  /auth/reset-password:
    post:
      $ref: '../swagger/paths/auth/reset-pwd.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /contacts:
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{contactId}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{contactId}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{contactId}/delete.yaml'
components:
  schemas:
    Contact:
      $ref: '../swagger/components/schemas/contact.yaml'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
